apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: garbage-classifier-traininig-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.21, pipelines.kubeflow.org/pipeline_compilation_time: '2023-05-17T19:55:22.295399',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Pipeline for training
      garbage classifier from scratch", "inputs": [{"name": "s3_access_key"}, {"name":
      "s3_secret_key"}, {"name": "s3_bucket"}, {"name": "s3_prefix"}, {"name": "wandb_api_key"}],
      "name": "garbage_classifier_traininig_pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.21}
spec:
  entrypoint: garbage-classifier-traininig-pipeline
  templates:
  - name: garbage-classifier-traininig-pipeline
    inputs:
      parameters:
      - {name: s3_access_key}
      - {name: s3_bucket}
      - {name: s3_prefix}
      - {name: s3_secret_key}
      - {name: wandb_api_key}
    dag:
      tasks:
      - name: load-data
        template: load-data
        arguments:
          parameters:
          - {name: s3_access_key, value: '{{inputs.parameters.s3_access_key}}'}
          - {name: s3_bucket, value: '{{inputs.parameters.s3_bucket}}'}
          - {name: s3_prefix, value: '{{inputs.parameters.s3_prefix}}'}
          - {name: s3_secret_key, value: '{{inputs.parameters.s3_secret_key}}'}
      - name: train
        template: train
        dependencies: [load-data]
        arguments:
          parameters:
          - {name: wandb_api_key, value: '{{inputs.parameters.wandb_api_key}}'}
          artifacts:
          - {name: load-data-test, from: '{{tasks.load-data.outputs.artifacts.load-data-test}}'}
          - {name: load-data-train, from: '{{tasks.load-data.outputs.artifacts.load-data-train}}'}
      - name: upload-model
        template: upload-model
        dependencies: [train]
        arguments:
          parameters:
          - {name: wandb_api_key, value: '{{inputs.parameters.wandb_api_key}}'}
          artifacts:
          - {name: train-config, from: '{{tasks.train.outputs.artifacts.train-config}}'}
          - {name: train-model, from: '{{tasks.train.outputs.artifacts.train-model}}'}
          - {name: train-model_card, from: '{{tasks.train.outputs.artifacts.train-model_card}}'}
  - name: load-data
    container:
      command: [python, garbage_classifier/cli.py, load-train-data, '{{inputs.parameters.s3_access_key}}',
        '{{inputs.parameters.s3_secret_key}}', '{{inputs.parameters.s3_bucket}}',
        '{{inputs.parameters.s3_prefix}}']
      image: rostyslavskliar/garbage-classifier-trainer:latest
    inputs:
      parameters:
      - {name: s3_access_key}
      - {name: s3_bucket}
      - {name: s3_prefix}
      - {name: s3_secret_key}
    outputs:
      artifacts:
      - {name: load-data-test, path: data/real-ds/test.tar.gz}
      - {name: load-data-train, path: data/real-ds/train.tar.gz}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.21
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/max_cache_staleness: P0D}
  - name: train
    container:
      command: [python, garbage_classifier/cli.py, train, garbage_classisier/data/config.json]
      env:
      - {name: WANDB_PROJECT, value: garbage-classifier}
      - {name: WANDB_API_KEY, value: '{{inputs.parameters.wandb_api_key}}'}
      image: rostyslavskliar/garbage-classifier-trainer:latest
    inputs:
      parameters:
      - {name: wandb_api_key}
      artifacts:
      - {name: load-data-train, path: data/real-ds/train.tar.gz}
      - {name: load-data-test, path: data/real-ds/test.tar.gz}
    outputs:
      artifacts:
      - {name: train-config, path: data/config.json}
      - {name: train-model, path: model/model.pth}
      - {name: train-model_card, path: data/real-ds/README.md}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.21
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  - name: upload-model
    container:
      command: [python, garbage_classifier/cli.py, upload-to-registry, garbage-classifier-kf,
        tmp/results]
      env:
      - {name: WANDB_PROJECT, value: garbage-classifier}
      - {name: WANDB_API_KEY, value: '{{inputs.parameters.wandb_api_key}}'}
      image: rostyslavskliar/garbage-classifier-trainer:latest
    inputs:
      parameters:
      - {name: wandb_api_key}
      artifacts:
      - {name: train-config, path: tmp/results/config.json}
      - {name: train-model, path: tmp/results/model.pth}
      - {name: train-model_card, path: tmp/results/README.md}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.21
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters:
    - {name: s3_access_key}
    - {name: s3_secret_key}
    - {name: s3_bucket}
    - {name: s3_prefix}
    - {name: wandb_api_key}
  serviceAccountName: pipeline-runner
