apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: uwg-garbage-classifier
  namespace: default
spec:
  annotations:
    seldon.io/rest-timeout: "60"
    seldon.io/grpc-timeout: "60"
  protocol: seldon
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: rostyslavskliar/uwg-app-seldon:latest
          name: classifier
          env:
          - name: GUNICORN_THREADS
            value: '1'
          - name: GUNICORN_WORKERS
            value: '1'
          - name: FLASK_SINGLE_THREADED
            value: '1'
          - name: SELDON_DEBUG
            value: '1'          
          - name: WANDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: WANDB_API_KEY
          - name: WANDB_PROJECT
            value: garbage-classifier
          - name: MODEL_ID
            value: uwg-classifier:v1
          - name: MODEL_PATH
            value: /tmp/model

    graph:
      name: classifier
      type: MODEL
    name: model
    replicas: 1
