name: garbage-classifier-training-image

on:
  push:
    branches:
      - feature/hw-7
    paths:
      - garbage_classifier/**

env:
  IMAGE_TRAINING: garbage-classifier-training

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: garbage_classifier/
          file: garbage_classifier/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_TRAINING }}:latest

