name: garbage-classifier-tests

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f garbage_classifier/requirements.txt ]; then pip install -r garbage_classifier/requirements.txt; fi

    - name: Run pytest
      run: |
        pytest garbage_classifier


