name: labelling-bot-deploy

on:
  push:
    branches:
      - feature/*

env:
  IMAGE_LABELLING_BOT: labelling-bot

jobs:
  build-and-push-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: labelling_bot/
          file: labelling_bot/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_LABELLING_BOT }}:latest
      - name: Docker pull and run from Hub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LABELLING_BOT_HOST }}
          username: ${{ secrets.LABELLING_BOT_SSH_USER }}
          key: ${{ secrets.LABELLING_BOT_SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if not already installed
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install docker -y
              sudo service docker start
              sudo usermod -a -G docker ec2-user
            fi
            
            # Start Docker service if not running
            if ! sudo service docker status &> /dev/null; then
              sudo service docker start
            fi
            
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_LABELLING_BOT }}:latest
            sudo docker stop ${{ env.IMAGE_LABELLING_BOT }} || true
            sudo docker rm ${{ env.IMAGE_LABELLING_BOT }} || true
            sudo docker run -d --name ${{ env.IMAGE_LABELLING_BOT }} ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_WEBAPP }}:latest


